### ISSUE TITLE
[Bug] 自动补全对大写英文失效

### ISSUE THREAD

**Issue by JieJiSS** [CircuitCoder/Console-Lite#13]
Patch: [here](https://github.com/JieJiSS/Console-Lite/commit/fe6ea86e6bdf176232bdd8792678f16178f8ecba#diff-c4a128808dd14509a0a2ec3fa901350fR10)

**Comment by CircuitCoder** [comment]
Thanks. I'm merging it with some minor adjustments.

**Comment by CircuitCoder** [comment]
Thanks. I'm merging it with some minor adjustments.
