### ISSUE TITLE
网站上不去

### ISSUE THREAD

**Issue by xige12138** [CircuitCoder/Console-Lite#15]
bro http://bjmun.org/是不是已经挂了

**Comment by CircuitCoder** [comment]
Hi there. Sorry for the delayed response. The server **is offline** right now.

We are making the effort to move the website onto servers within mainland China for faster speed, as some suffered from the slow connection to our Japanese server. To do so, we need to apply for an ICP license, whose process requires us to bring the domain down for a few months.

Meanwhile, we are separating Console Lite from BJMUN. Instead we are forming a new team, dedicated to development of software related to MUN conferences. Our new domain name is also under the process of ICP licensing, but it's finishing soon. We will update the documentation as soon as the new website is up, and we expect that the auto-update logic will continue to work.

**Comment by CircuitCoder** [comment]
I've created a new issue #16 regarding the website issue. I'm closing this issue for now. If you have further question, you can reopen it or directly add a new comment below.

Thank you for your support for our product.

**Comment by xige12138** [comment]
OK. Actually you can use Chinese because we're both Chinese.

Liu Xiaoyi <notifications@github.com> 于 2018年8月22日周三 上午2:16写道：

**Comment by CircuitCoder** [comment]
The new website is up. https://easymun.com/console-lite
